# Config file


[OPTIONS]
# 0 -> Crotchets
# 1 -> Quavers
# 2 -> Semiquavers
# 3 -> Demisemiquavers
# etc.
note_depth_power = 2

export_type = "pdf" # pdf or png





[ADVANCED_OPTIONS]
onset_to_beat_lag = 0.06
model = "models\\4VOICE.mdl"




[ENVIRONMENT]
musescore4_path = "C:\\Program Files\\MuseScore 4\\bin\\MuseScore4.exe"






[DEBUG]
generate_sheet_music = false
graphing = false
save_model = false
show_network_graphs = true