# Config file


[OPTIONS]
# 0 -> Crotchets
# 1 -> Quavers
# 2 -> Semiquavers
# 3 -> Demisemiquavers
# etc.
note_depth = 2

export_type = "pdf" # pdf or png



[ENVIRONMENT]
musescore4_path = "C:\\Program Files\\MuseScore 4\\bin\\MuseScore4.exe"








[ADVANCED_OPTIONS]
onset_to_beat_lag = 0.06
model = "FINAL.mdl"
training_device = "cuda"
use_cuda_if_available = true
key_profile = "data\\Krumhansl-Kessler.csv"

output_cleanly = false
clear_temp = false
note_detection_threshold = 1 #0.5




[DEBUG]
generate_sheet_music = true
graphing = false
save_model = true
show_network_graphs = true
spin = true