# Config file


[OPTIONS]
# 0 -> Crotchets (Quarters)
# 1 -> Quavers  (Eighths)
# 2 -> Semiquavers (Sixteenths)
# 3 -> Demisemiquavers (Thirtyseconds)
# etc.
note_depth = 2

export_type = "pdf" # pdf or png



[ENVIRONMENT]
musescore4_path = "C:\\Program Files\\MuseScore 4\\bin\\MuseScore4.exe" # Use double backslash!








[ADVANCED_OPTIONS]
onset_to_beat_lag = 0.06
model = "ArezzoRandom.mdl"
training_device = "cuda"
use_cuda_if_available = true
key_profile = "data\\Krumhansl-Kessler.csv"

output_cleanly = false
clear_temp = false
note_detection_threshold = 2 #0.5

test_save_sheet_music = false


[DEBUG]
generate_sheet_music = true
graphing = false
save_model = false
show_network_graphs = true
spin = true
blanket_disable_debug_print = false